# ========== build ==========
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia solución y proyecto (ajusta nombres si difieren)
COPY MiniCoreComisiones.sln ./
COPY MiniCoreComisiones/ MiniCoreComisiones/

# Restore + Publish
RUN dotnet restore
RUN dotnet publish MiniCoreComisiones/MiniCoreComisiones.csproj -c Release -o /app/out

# ========== runtime ==========
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out ./

# ASP.NET escucha dentro del contenedor en 8080
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "MiniCoreComisiones.dll"]
